services:
  - type: web
    name: bfcinema
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: BACKBLAZE_KEY_ID
        sync: false
      - key: BACKBLAZE_APPLICATION_KEY
        sync: false
      - key: BACKBLAZE_BUCKET
        value: bfcinema
      - key: BACKBLAZE_ENDPOINT
        value: https://s3.eu-central-003.backblazeb2.com
      - key: ADMIN_PASSWORD
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
